URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/static
Exception on /static/d3.word.js [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 20, in serve_static
    return send_from_directory(os.path.join(root_dir, 'Learning','static'), filename)
NameError: global name 'send_from_directory' is not defined
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/static
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/static
URL is d3.word.js
Exception on /static/d3.word.js [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 20, in serve_static
    app.logger.warning('Input to send_from_directory - ' + str(s.path.join(root_dir, 'WordFreq','static')))
NameError: global name 's' is not defined
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/WordFreq/static
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/WordFreq/static
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/WordFreq/static
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/WordFreq/static
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/WordFreq/static
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/WordFreq/static
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/WordFreq/static
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/WordFreq/static
URL is d3.word.js
Input to send_from_directory - /Users/manishdwibedy/Documents/Codes/Hackathon/HackPoly/photolytiq/POC/WordFreq/static
